#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GO-TermFinder
version:      0.85
version_from: VERSION
installdirs:  site
license:      open_source
requires:
    GD:                            0
    Test::More:                    0
    CGI:                           0
    Storable:                      1.0.1.12
    GraphViz:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
